Data Link: https://www.kaggle.com/datasets/uciml/pima-indians-diabetes-database

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("Pima_Indians_Diabetes.csv")

In [3]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [5]:
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [6]:
X

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [7]:
X.shape

(768, 8)

In [8]:
y.shape

(768,)

In [9]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [10]:
X = scaler.fit_transform(X)

In [11]:
X

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

In [14]:
X_train

array([[-0.54791859, -1.15469351, -3.57259724, ..., -4.06047387,
        -0.50700636, -1.04154944],
       [ 1.53084665, -0.27837344,  0.66661825, ..., -0.48135115,
         2.44666971,  1.4259954 ],
       [-0.84488505,  0.56664949, -1.19450074, ..., -0.41789153,
         0.55003518, -0.95646168],
       ...,
       [ 1.82781311, -0.62264204,  0.87340925, ...,  1.72704372,
         2.00573238,  0.40494237],
       [-1.14185152,  0.62924378, -3.57259724, ...,  1.32090213,
        -0.8059981 , -0.36084741],
       [-1.14185152,  0.12848945,  1.39038675, ..., -1.20479085,
        -0.63385134, -1.04154944]])

In [15]:
y_train

array([0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,

In [16]:
import tensorflow as tf

In [17]:
LAYERS = [
    tf.keras.layers.Dense(32, activation='relu', input_dim = 8),
    tf.keras.layers.Dense(1,activation='sigmoid')
]

model = tf.keras.models.Sequential(LAYERS)

In [18]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                288       
                                                                 
 dense_1 (Dense)             (None, 1)                 33        
                                                                 
Total params: 321
Trainable params: 321
Non-trainable params: 0
_________________________________________________________________


In [19]:
LOSS_FUNCTION = 'binary_crossentropy'
OPTIMIZER = 'Adam'
METRICS = ['accuracy']



model.compile(loss=LOSS_FUNCTION,
              optimizer=OPTIMIZER,
              metrics= METRICS)

In [20]:
model.fit(X_train, y_train, batch_size=32, epochs=10, validation_data=(X_test, y_test))

Epoch 1/10
20/20 [==============================] - 2s 13ms/step - loss: 0.6048 - accuracy: 0.7134 - val_loss: 0.6033 - val_accuracy: 0.7143
Epoch 2/10
20/20 [==============================] - 0s 5ms/step - loss: 0.5654 - accuracy: 0.7492 - val_loss: 0.5747 - val_accuracy: 0.7338
Epoch 3/10
20/20 [==============================] - 0s 5ms/step - loss: 0.5385 - accuracy: 0.7638 - val_loss: 0.5546 - val_accuracy: 0.7662
Epoch 4/10
20/20 [==============================] - 0s 5ms/step - loss: 0.5195 - accuracy: 0.7720 - val_loss: 0.5408 - val_accuracy: 0.7662
Epoch 5/10
20/20 [==============================] - 0s 16ms/step - loss: 0.5049 - accuracy: 0.7801 - val_loss: 0.5300 - val_accuracy: 0.7727
Epoch 6/10
20/20 [==============================] - 0s 9ms/step - loss: 0.4930 - accuracy: 0.7785 - val_loss: 0.5208 - val_accuracy: 0.7792
Epoch 7/10
20/20 [==============================] - 0s 5ms/step - loss: 0.4829 - accuracy: 0.7769 - val_loss: 0.5154 - val_accuracy: 0.7857
Epoch 8/10
20/20 [

## 1.How to Select Best Optimizer
## 2.How to Select Number of Nodes/Neurons in a Layer
## 3.How to Select Number of Layers
## 4.All in One Model

In [ ]:
!pip install -U keras-tuner

In [21]:
import keras_tuner as kt

## 1.How to Select Best Optimizer

In [22]:
def build_model(hp):
    LAYERS = [
      tf.keras.layers.Dense(32, activation='relu', input_dim = 8),
      tf.keras.layers.Dense(1,activation='sigmoid')
      ]

    model = tf.keras.models.Sequential(LAYERS)

    LOSS_FUNCTION = 'binary_crossentropy'
    OPTIMIZER = hp.Choice('optimizer', values = ['adam','sgd','rmsprop','adadelta'])
    METRICS = ['accuracy']



    model.compile(loss=LOSS_FUNCTION,
                optimizer=OPTIMIZER,
                metrics= METRICS)
    return model


In [23]:
tuner = kt.RandomSearch(build_model,
                        objective = 'val_accuracy',
                        max_trials=5)

In [24]:
tuner.search(X_train,y_train, epochs=5, validation_data=(X_test,y_test))

Trial 4 Complete [00h 00m 02s]
val_accuracy: 0.4740259647369385

Best val_accuracy So Far: 0.7727272510528564
Total elapsed time: 00h 00m 08s


In [25]:
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'adam'}

In [26]:
model = tuner.get_best_models(num_models=1)[0]

In [27]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                288       
                                                                 
 dense_1 (Dense)             (None, 1)                 33        
                                                                 
Total params: 321
Trainable params: 321
Non-trainable params: 0
_________________________________________________________________


In [28]:
model.fit(X_train,y_train, epochs=10, initial_epoch=6, validation_data=(X_test,y_test))

Epoch 7/10
20/20 [==============================] - 1s 12ms/step - loss: 0.5317 - accuracy: 0.7557 - val_loss: 0.5309 - val_accuracy: 0.7987
Epoch 8/10
20/20 [==============================] - 0s 6ms/step - loss: 0.5148 - accuracy: 0.7622 - val_loss: 0.5223 - val_accuracy: 0.7987
Epoch 9/10
20/20 [==============================] - 0s 5ms/step - loss: 0.5022 - accuracy: 0.7655 - val_loss: 0.5155 - val_accuracy: 0.7987
Epoch 10/10
20/20 [==============================] - 0s 5ms/step - loss: 0.4918 - accuracy: 0.7671 - val_loss: 0.5085 - val_accuracy: 0.7922


## 2.How to Select Number of Nodes/Neurons in a Layer

In [29]:
def build_model(hp):

    units = hp.Int('units', min_value = 8, max_value =128, step = 8)

    LAYERS = [
      tf.keras.layers.Dense(units=units, activation='relu', input_dim = 8),
      tf.keras.layers.Dense(1,activation='sigmoid')
      ]

    model = tf.keras.models.Sequential(LAYERS)

    LOSS_FUNCTION = 'binary_crossentropy'
    OPTIMIZER = 'rmsprop'
    METRICS = ['accuracy']



    model.compile(loss=LOSS_FUNCTION,
                optimizer=OPTIMIZER,
                metrics= METRICS)
    return model

In [30]:
tuner = kt.RandomSearch(build_model,
                        objective = 'val_accuracy',
                        max_trials=5,
                        directory='mydir')

In [31]:
tuner.search(X_train,y_train, epochs=5, validation_data=(X_test,y_test))

Trial 5 Complete [00h 00m 03s]
val_accuracy: 0.7532467246055603

Best val_accuracy So Far: 0.7792207598686218
Total elapsed time: 00h 00m 11s


In [32]:
tuner.get_best_hyperparameters()[0].values

{'units': 72}

In [33]:
model = tuner.get_best_models(num_models=1)[0]

In [34]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 72)                648       
                                                                 
 dense_1 (Dense)             (None, 1)                 73        
                                                                 
Total params: 721
Trainable params: 721
Non-trainable params: 0
_________________________________________________________________


## 3.How to Select Number of Layers

In [35]:
import tensorflow as tf
import keras
from keras.layers import Dense
from keras.models import Sequential

In [36]:
def build_model(hp):
  model = Sequential()
  model.add(Dense(88, activation = 'relu', input_dim=8))

  for i in range(hp.Int('num_layers', min_value=1, max_value=10)):
    model.add(Dense(88, activation = 'relu'))

  model.add(Dense(1, activation = 'sigmoid'))

  LOSS_FUNCTION = 'binary_crossentropy'
  OPTIMIZER = 'rmsprop'
  METRICS = ['accuracy']

  model.compile(loss= LOSS_FUNCTION,
                optimizer= OPTIMIZER,
                metrics= METRICS)

  return model

In [37]:
tuner = kt.RandomSearch(build_model,
                        objective = 'val_accuracy',
                        max_trials=5,
                        directory='mydir1')

In [38]:
tuner.search(X_train,y_train, epochs=5, validation_data=(X_test,y_test))

Trial 5 Complete [00h 00m 03s]
val_accuracy: 0.7272727489471436

Best val_accuracy So Far: 0.7922077775001526
Total elapsed time: 00h 00m 17s


In [39]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 4}

In [40]:
model = tuner.get_best_models(num_models=1)[0]

In [41]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 88)                792       
                                                                 
 dense_1 (Dense)             (None, 88)                7832      
                                                                 
 dense_2 (Dense)             (None, 88)                7832      
                                                                 
 dense_3 (Dense)             (None, 88)                7832      
                                                                 
 dense_4 (Dense)             (None, 88)                7832      
                                                                 
 dense_5 (Dense)             (None, 1)                 89        
                                                                 
Total params: 32,209
Trainable params: 32,209
Non-traina

## 4.All in One Model

In [42]:
def build_model(hp):

  model = Sequential()

  counter = 0

  for i in range(hp.Int('num_layers',min_value= 1,max_value=10)):
    if counter == 0:
      model.add(Dense(hp.Int('units' + str(i),min_value= 8,max_value=128, step=8),
                      activation=hp.Choice('activation' + str(i), values=['relu', 'tanh']),
                      input_dim=8))


    else:
      model.add(Dense(hp.Int('units' + str(i),min_value= 8,max_value=128, step=8),
                      activation=hp.Choice('activation' + str(i), values=['relu', 'tanh'])))

    counter += 1


  model.add(Dense(1, activation='sigmoid'))


  LOSS_FUNCTION = "binary_crossentropy"
  OPTIMIZER = hp.Choice('optimizer', values = ['adam', 'sgd', 'rmsprop', 'adadelta'])
  METRICS = ["accuracy"]

  model.compile(loss=LOSS_FUNCTION,
                optimizer=OPTIMIZER,
                metrics=METRICS)

  return model

In [43]:
tuner = kt.RandomSearch(build_model,
                        objective = 'val_accuracy',
                        max_trials=5,
                        directory='mydir2')

In [44]:
tuner.search(X_train,y_train, epochs=5, validation_data=(X_test,y_test))

Trial 5 Complete [00h 00m 04s]
val_accuracy: 0.350649356842041

Best val_accuracy So Far: 0.7662337422370911
Total elapsed time: 00h 00m 26s


In [45]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 6,
 'units0': 64,
 'activation0': 'tanh',
 'optimizer': 'adam',
 'units1': 40,
 'activation1': 'tanh',
 'units2': 24,
 'activation2': 'tanh',
 'units3': 24,
 'activation3': 'relu',
 'units4': 104,
 'activation4': 'relu',
 'units5': 32,
 'activation5': 'tanh',
 'units6': 104,
 'activation6': 'relu',
 'units7': 88,
 'activation7': 'relu',
 'units8': 80,
 'activation8': 'tanh'}

In [46]:
model = tuner.get_best_models(num_models=1)[0]

In [47]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 64)                576       
                                                                 
 dense_1 (Dense)             (None, 40)                2600      
                                                                 
 dense_2 (Dense)             (None, 24)                984       
                                                                 
 dense_3 (Dense)             (None, 24)                600       
                                                                 
 dense_4 (Dense)             (None, 104)               2600      
                                                                 
 dense_5 (Dense)             (None, 32)                3360      
                                                                 
 dense_6 (Dense)             (None, 1)                 3

In [48]:
model.fit(X_train, y_train, epochs=10, initial_epoch=6, validation_data=(X_test, y_test))

Epoch 7/10
20/20 [==============================] - 3s 16ms/step - loss: 0.4484 - accuracy: 0.7769 - val_loss: 0.5004 - val_accuracy: 0.7532
Epoch 8/10
20/20 [==============================] - 0s 6ms/step - loss: 0.4472 - accuracy: 0.7801 - val_loss: 0.4963 - val_accuracy: 0.7662
Epoch 9/10
20/20 [==============================] - 0s 7ms/step - loss: 0.4397 - accuracy: 0.7883 - val_loss: 0.5042 - val_accuracy: 0.7468
Epoch 10/10
20/20 [==============================] - 0s 6ms/step - loss: 0.4350 - accuracy: 0.7883 - val_loss: 0.5041 - val_accuracy: 0.7532
